
# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Compile
      run: mvn compile
    - name: Test
      run: mvn test
    - name: Build
      run: mvn package
    - name: Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Floating-Container-0.0.1-SNAPSHOT
        path: /home/runner/work/floating-container/floating-container/target/floating-container-0.0.1-SNAPSHOT-jar-with-dependencies.jar
